GET https://6d29-175-124-145-87.ngrok-free.app/api/auth/google/callback?code=4%2F0ASVgi3KDRQr4a2Jgq4E1NrRRXXO-5JGimrnpp8pPJShesjnWNUBv2XYjxyNVvi2fe_9NJg

###
GET https://accounts.google.com/o/oauth2/auth?
    client_id=923892619075-ohdkn9r30q6hkrogp0c8uh7ujl2h9hpv.apps.googleusercontent.com
    &redirect_uri=https://6d29-175-124-145-87.ngrok-free.app/api/auth/google/callback
    &response_type=code
    &scope=openid%20profile%20email
    &access_type=offline

###
GET https://accounts.google.com/o/oauth2/auth?
    client_id=923892619075-ohdkn9r30q6hkrogp0c8uh7ujl2h9hpv.apps.googleusercontent.com&
    redirect_uri=https://6d29-175-124-145-87.ngrok-free.app/api/auth/google/callback&response_type=code&
    scope=openid%20profile%20email&access_type=offline